zone               = "europe-west1a"
name               = "bastion"
project            = "exampleA"
subnetwork         = "exampleA-subnets"
subnetwork_project = "exampleA"
region             = "europe-west1"
