---
name: Pull Request
on:
  pull_request:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
# holden:ignore:HLD_CI_017: references to our workflow
  pr:
    uses: JamesWoolfenden/.github/.github/workflows/terraform-pr-gcp.yml@main
    with:
      service_account: terraform-gcp-bastion@pike-477416.iam.gserviceaccount.com
